/*
 * TrafficLightsControl_private.h
 *
 *  Created on: Dec 29, 2024
 *      Author: s_a_a
 */

#ifndef APP_TRAFFICLIGHTS_INC_TRAFFICLIGHTSCONTROL_PRIVATE_H_
#define APP_TRAFFICLIGHTS_INC_TRAFFICLIGHTSCONTROL_PRIVATE_H_



#endif /* APP_TRAFFICLIGHTS_INC_TRAFFICLIGHTSCONTROL_PRIVATE_H_ */
